services:
  backend:
    build: ./backend
    hostname: "backend"
    ports:
      - "5000:5000"
    networks:
      - app-network
    env_file:
      - frontend/.env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - frontend/.env
  mongodb:
    image: mongo:latest
    container_name: mongodb
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - "27017:27017"
    volumes:
      - type: tmpfs
        target: /data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - app-network
    env_file:
      - frontend/.env

networks:
  app-network:
    driver: bridge
